---
- name: Verificando se o container existe
  docker_container_info:
    name: "{{ grafana_container_name }}"
  register: grafana_result

- name: Grafana
  block:
    - name: Download da imagem
      docker_image:
        name: "{{ grafana_image }}"
        source: pull

    - name: Iniciando o Container
      docker_container:
        name: "{{ grafana_container_name }}"
        image: "{{ grafana_image }}"
        state: started
        recreate: yes
        restart: yes
        restart_policy: unless-stopped
        networks_cli_compatible: yes
        networks:
          - name: zabbix-stack
            links: "{{ zabbix_web_container_name }}:zabbix-console-web"
        links:
          - "{{ zabbix_web_container_name }}:zabbix-console-web"
        ports:
          - "{{ grafana_port }}"
  rescue:
    - name:
      debug:
        msg: "Please check your internet connection"
  when:
    - (grafana_result.exists != true)