---
- name: Verify if grafana container exists
  docker_container_info:
    name: "{{ grafana_container_name }}"
  register: grafana_result

- name: Grafana
  block:
    - name: Download grafana image
      docker_image:
        name: "{{ grafana_image }}"
        source: pull

    - name: Create grafana container
      docker_container:
        name: "{{ grafana_container_name }}"
        image: "{{ grafana_image }}"
        state: started
        container_default_behavior: no_defaults        
        recreate: yes
        restart: yes
        restart_policy: unless-stopped
        networks_cli_compatible: yes
        network_mode: zabbix-stack
        links:
          - "{{ zabbix_web_container_name }}:zabbix-console-web"
        ports:
          - "{{ grafana_port }}"
  rescue:
    - name: Grafana container Failed
      ansible.builtin.fail:
        msg: ansible_failed_result
  when: grafana_result.exists == false
