{
 "title": "Zabbix - Oracle Database",
 "description": "Dashboard based on information collected from Zabbix Server for Linux environment.  In this panel you can select a group and then the specific host from which we want to view the collected data.\n",
 "tags": [ "Linux" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Grupo",
    "label": "Grupo",
    "query": {}
   },
   {
    "name": "Host",
    "label": "Host",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Oracle Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Database Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": { "filter": "Oracle" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Host" },
     "item": { "filter": "Alive" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Active State",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Oracle" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Host" },
     "item": { "filter": "Instance ACTIVE_STATE XE" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Tablespace Percent",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": { "filter": "Oracle" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Host" },
     "item": { "filter": "/^Tablespace .*(%)/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Oracle" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Host" },
     "item": { "filter": "Uptime" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Session Inactive",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Oracle" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Host" },
     "item": { "filter": "Session Inactive" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Session System",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Oracle" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Host" },
     "item": { "filter": "Session System" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Blocking Sessions",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Oracle" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Host" },
     "item": { "filter": "Blocking Sessions" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Session Active",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Oracle" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Host" },
     "item": { "filter": "Session Active" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Oracle" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Host" },
     "item": { "filter": "Sessions" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Oracle" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Host" },
     "item": { "filter": "DB Version" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Tablespace Space",
   "type": "stat",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Oracle" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Host" },
     "item": { "filter": "/^Tablespace .*(bytes)/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Edition",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Oracle" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Host" },
     "item": { "filter": "Instance EDITION XE" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Pin hit ratio",
   "type": "stat",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Oracle" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Host" },
     "item": { "filter": "/Pin hit ratio/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Database Type",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Oracle" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Host" },
     "item": { "filter": "Instance DATABASE_TYPE XE" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "PHI/O Datafile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "Oracle" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Host" },
     "item": { "filter": "/PHI/O Datafile/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "PGA",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "application": { "filter": "Oracle" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Host" },
     "item": { "filter": "PGA" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "SGA",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "application": { "filter": "Oracle" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Host" },
     "item": { "filter": "/SGA/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Pool",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "application": { "filter": "Oracle" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Host" },
     "item": { "filter": "/Pool/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}