---
all:
  vars:
    zabbix_web_server_name: "ZABBIX SERVER"
    zabbix_server_ip: 
    zabbix_agent_port: 
    mysql_zbx_db_pwd: ""
    mysql_root_pwd: ""
  hosts:
    zabbix-server:
      ansible_host: 
  children:
    server:
      hosts:
    agent_linux:
      hosts:
    agent_windows:
      hosts: