---
all:
  vars:
    zabbix_server_ip: "1.2.3.4"
    zabbix_agent_port: "10050"
    mysql_zbx_db_pwd: ""
    mysql_root_pwd: ""
  hosts:
    zabbix-server:
      ansible_host: 1.2.3.4
  children:
    server:
      hosts:
    agent_linux:
      hosts:
    agent_windows:
      hosts: