---
- name: Verify if MySQL container is running
  community.docker.docker_container_info:
    name: "{{ mysql_container_name }}"
  register: mysql_server_result

- name: Download da imagem
  block:
    - name: Dockerhub
      docker_image:
        name: "{{ mysql_image }}"
        source: pull

    - name: Created Network
      docker_network:
        name: zabbix-stack
        appends: yes

    - name: Created volume
      community.docker.docker_volume:
        name: mysql-server
        recreate: options-changed
        state: present

    - name: Initializing the MySQL container
      community.docker.docker_container:
        name: mysql-server
        image: "{{ mysql_image }}"
        state: started
        container_default_behavior: no_defaults
        recreate: yes
        restart: yes
        networks_cli_compatible: yes
        network_mode: zabbix-stack
        volumes:
          - mysql-server:/var/lib/mysql
        restart_policy: unless-stopped
        command: "{{ mysql_command }}"
        env:
          MYSQL_DATABASE: "{{ mysql_zbx_db }}"
          MYSQL_USER: "{{ mysql_zbx_db_user }}"
          MYSQL_PASSWORD: "{{ mysql_zbx_db_pwd }}"
          MYSQL_ROOT_PASSWORD: "{{ mysql_root_pwd }}"
  rescue:
    - name: Fail deploy MySQL
      ansible.builtin.fail:
        msg: "Deploy MySQL failed"
  when: mysql_server_result.exists == false
