---
- name: Verificando se o container existe
  docker_container_info:
    name: "{{ mysql_container_name }}"
  register: mysql_server_result

- name: Download da imagem
  block:
    - name: Dockerhub
      docker_image:
        name: "{{ mysql_image }}"
        source: pull

    - name: Criando Network
      docker_network:
        name: zabbix-stack
        appends: yes

    - name: Criando volume
      docker_volume:
        name: mysql-server
        state: present

    - name: Iniciando o Container
      docker_container:
        name: mysql-server
        image: "{{ mysql_image }}"
        state: started
        recreate: yes
        restart: yes
        networks_cli_compatible: yes
        networks:
          - name: zabbix-stack
        volumes:
          - mysql-server:/var/lib/mysql
        restart_policy: unless-stopped
        command: "{{ mysql_command }}"
        env:
          MYSQL_DATABASE: "{{ mysql_zbx_db }}"
          MYSQL_USER: "{{ mysql_zbx_db_user }}"
          MYSQL_PASSWORD: "{{ mysql_zbx_db_pwd }}"
          MYSQL_ROOT_PASSWORD: "{{ mysql_root_pwd }}"
  rescue:
    - name:
      debug:
        msg: "Please check your internet connection"
  when:    
    - (mysql_server_result.exists != true)