---
- name: Verify if Zabbix Server container is running
  docker_container_info:
    name: "{{ zabbix_server_container_name }}"
  register: zabbix_server_result

- name: Zabbix Server
  block:
    - name: Download image
      docker_image:
        name: "{{ zabbix_server_image }}"
        source: pull

    - name: Criando volume
      docker_volume:
        name: "{{ item }}"
        state: present
      loop:
        - zabbix-server-alertscripts
        - zabbix-server-externalscripts
        - zabbix-server-enc
        - zabbix-server-export
        - zabbix-server-mibs
        - zabbix-server-modules
        - zabbix-server-snmptraps
        - zabbix-server-ssh_keys
        - zabbix-server-certs
        - zabbix-server-keys
        - zabbix-server-ssl_ca

    - name: Inicialize Container Zabbix Server
      docker_container:
        name: "{{ zabbix_server_container_name }}"
        image: "{{ zabbix_server_image }}"
        state: started
        container_default_behavior: no_defaults
        restart: yes
        recreate: yes
        restart_policy: unless-stopped
        networks_cli_compatible: yes
        network_mode: zabbix-stack
        volumes:
          - zabbix-server-alertscripts:/usr/lib/zabbix/alertscripts
          - zabbix-server-externalscripts:/usr/lib/zabbix/externalscripts
          - zabbix-server-enc:/var/lib/zabbix/enc
          - zabbix-server-export:/var/lib/zabbix/export
          - zabbix-server-mibs:/var/lib/zabbix/mibs
          - zabbix-server-modules:/var/lib/zabbix/modules
          - zabbix-server-snmptraps:/var/lib/zabbix/snmptraps
          - zabbix-server-ssh_keys:/var/lib/zabbix/ssh_keys
          - zabbix-server-certs:/var/lib/zabbix/ssl/certs
          - zabbix-server-keys:/var/lib/zabbix/ssl/keys
          - zabbix-server-ssl_ca:/var/lib/zabbix/ssl/ssl_ca
        links:
          - "{{ mysql_container_name }}:mysql"
        ports:
          - "{{ zabbix_server_ports }}"
        env:
          DB_SERVER_HOST: "{{ zabbix_server_db_host }}"
          MYSQL_DATABASE: "{{ mysql_zbx_db }}"
          MYSQL_USER: "{{ mysql_zbx_db_user }}"
          MYSQL_PASSWORD: "{{ mysql_zbx_db_pwd }}"
          MYSQL_ROOT_PASSWORD: "{{ mysql_root_pwd }}"
          ZBX_CACHESIZE: "{{ zabbix_server_cachesize }}"
  rescue:
    - name: Zabbix Server Failed
      ansible.builtin.fail:
        msg: ansible_failed_result
  when: zabbix_server_result.exists == false

- name: Zabbix Agent for Server
  block:
    - name: Zabbix Agent
      docker_image:
        name: "{{ zabbix_agent_image }}"
        source: pull

    - name: Initialize Zabbix Agent
      docker_container:
        name: "{{ zabbix_agent_container_name }}"
        image: "{{ zabbix_agent_image }}"
        state: started
        container_default_behavior: no_defaults
        restart: yes
        recreate: yes
        restart_policy: unless-stopped
        networks_cli_compatible: yes
        network_mode: zabbix-stack
        links:
          - "{{ zabbix_server_container_name }}:zabbix-server-mysql"
        env:
          ZBX_METADATA: "{{ zabbix_host_metadata_linux }}"
          ZBX_ACTIVE_ALLOW: "{{ zabbix_agent_active_allow }}"
          ZBX_HOSTNAME: "{{ zabbix_agent_hostname }}"
          ZBX_STARTAGENTS: "{{ zabbix_agent_startagents }}"
  rescue:
    - name: Zabbix Agent Failed
      ansible.builtin.fail:
        msg: ansible_failed_result
  when: zabbix_server_result.exists == false
