---
- name: Verify if Zabbix Web Container is running
  docker_container_info:
    name: "{{ zabbix_web_container_name }}"
  register: zabbix_web_result

- name: Zabbix Web
  block:
    - name: Docker Image Zabbix Web
      community.docker.docker_image:
        name: "{{ zabbix_web_image }}"
        source: pull

    - name: Create volume for Zabbix Web
      community.docker.docker_volume:
        name: "{{ item }}"
        state: present
      loop:
        - zabbix-web-nginx
        - zabbix-web-modules

    - name: Initialize Zabbix Web
      community.docker.docker_container:
        name: "{{ zabbix_web_container_name }}"
        image: "{{ zabbix_web_image }}"
        state: started
        container_default_behavior: no_defaults        
        restart: yes
        recreate: yes
        restart_policy: unless-stopped
        volumes:
          - zabbix-web-nginx:/etc/ssl/nginx
          - zabbix-web-modules:/usr/share/zabbix/modules
        networks_cli_compatible: yes
        network_mode: zabbix-stack
        links:
          - "{{ mysql_container_name }}:mysql-server"
          - "{{ zabbix_server_container_name }}:zabbix-server-mysql"
        ports:
          - "{{ zabbix_exp_ports }}"
        env:
          ZBX_SERVER_NAME: "{{ zabbix_web_server_name }}"
          ZBX_SERVER_HOST: "{{ zabbix_server_container_name }}"
          DB_SERVER_HOST: "{{ zabbix_server_db_host }}"
          MYSQL_DATABASE: "{{ mysql_zbx_db }}"
          MYSQL_USER: "{{ mysql_zbx_db_user }}"
          MYSQL_PASSWORD: "{{ mysql_zbx_db_pwd }}"
          MYSQL_ROOT_PASSWORD: "{{ mysql_root_pwd }}"
          PHP_TZ: "{{ zabbix_web_php_tz }}"
  rescue:
    - name: Zabbix Web Fail
      ansible.builtin.fail:
        msg: ansible_failed_result
  when: zabbix_web_result.exists == false
