---
- name: "{{ zabbix_web_container_name }} - Verificando se o container existe"
  docker_container_info:
    name: "{{ zabbix_web_container_name }}"
  register: zabbix_web_result

- name: Zabbix Web
  block:
    - name: "{{ zabbix_web_container_name }} - Dockerhub"
      docker_image:
        name: "{{ zabbix_web_image }}"
        source: pull

    - name: Criando volume
      docker_volume:
        name: "{{ item }}"
        state: present
      loop:
        - zabbix-web-nginx
        - zabbix-web-modules

    - name: "{{ zabbix_web_container_name }} - Iniciando container"
      docker_container:
        name: "{{ zabbix_web_container_name }}"
        image: "{{ zabbix_web_image }}"
        state: started
        restart: yes
        recreate: yes
        restart_policy: unless-stopped
        volumes:
          - zabbix-web-nginx:/etc/ssl/nginx
          - zabbix-web-modules:/usr/share/zabbix/modules
        networks_cli_compatible: yes
        networks:
          - name: zabbix-stack
        links:
          - "{{ mysql_container_name }}:mysql-server"
          - "{{ zabbix_server_container_name }}:zabbix-server-mysql"
        ports:
          - "{{ zabbix_exp_ports }}"
        env:
          ZBX_SERVER_NAME: "{{ zabbix_web_server_name }}"
          ZBX_SERVER_HOST: "{{ zabbix_server_container_name }}"
          DB_SERVER_HOST: "{{ zabbix_server_db_host }}"
          MYSQL_DATABASE: "{{ mysql_zbx_db }}"
          MYSQL_USER: "{{ mysql_zbx_db_user }}"
          MYSQL_PASSWORD: "{{ mysql_zbx_db_pwd }}"
          MYSQL_ROOT_PASSWORD: "{{ mysql_root_pwd }}"
          PHP_TZ: "{{ zabbix_web_php_tz }}"
  rescue:
    - name:
      debug:
        msg: "Please check your internet connection"
  when:
    - (zabbix_web_result.exists !=  true)