---
- name: Update hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"

- name: Add hostname to /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "{{ hostvars[item]['ansible_host'] }} {{ hostvars[item]['inventory_hostname'] }}"
  loop: "{{ groups['all'] }}"

- name: Enabled IP forward
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes

- name: Prepare the system for installation
  block:
    - name: Update system
      ansible.builtin.package:
        name: "*"
        state: latest


    - name: Install essential packages
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop: "{{ packages.to_install }}"

    - name: Install Module Pip
      ansible.builtin.pip:
        name:
          - "{{ item }}"
        executable: pip3
      loop: "{{ pip.to_install }}"

  rescue:
    - name: Failed to install packages
      ansible.builtin.fail:
        msg: "Failed to install packages"

- name: Docker
  block:
    - name: Verificando pre requisitos
      ansible.builtin.package_facts:
        manager: auto

    - name: Verificando se o repositório Docker existe
      ansible.builtin.stat:
        path: "{{ path_docker_repo }}"
      register: docker_repo

    - name: Habilitando o Repositório do Docker
      ansible.builtin.yum_repository:
        name: docker
        description: Docker CE Stable - $basearch
        baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
        gpgcheck: yes
        enabled: yes
        gpgkey: https://download.docker.com/linux/centos/gpg
      when: docker_repo.stat.exists == false

    - name: Instalando Docker
      ansible.builtin.yum:
        name: docker-ce
        state: present

    - name: Enable docker service on systemctl
      ansible.builtin.systemd:
        name: docker
        enabled: yes
        state: started

  rescue:
    - name: "Error: {{ ansible_failed_result.msg }}"
      ansible.builtin.fail:
        msg: "Error: {{ ansible_failed_result.msg }}"
