---
- name: Ajustando o Hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: "Atualizando /etc/hosts - {{ inventory_hostname }}"
  lineinfile:
    path: /etc/hosts
    line: "{{ hostvars[item]['ansible_host'] }} {{ hostvars[item]['inventory_hostname'] }}"
  loop: "{{ groups['all'] }}"

- sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes

- name: Preparando o sistema operacional
  block:
    - name: Atualizando o Sistema
      package:
        name: "*"
        state: latest
      ignore_errors: yes

    - name: Instalando pacotes essenciais
      package:
        name:  "{{ item }}"
        state: present
      loop: "{{ packages.to_install }}"
      ignore_errors: yes

    - name: Modulo Pip
      pip:
        name:
          - pip
          - docker
        extra_args: --upgrade
      ignore_errors: yes

- name: Docker
  block:
    - name: Verificando pre requisitos
      package_facts:
        manager: auto

    - name: Verificando se o repositório Docker existe
      stat:
        path: "{{ path_docker_repo }}"
      register: docker_repo

    - name: Habilitando o Repositório do Docker
      yum_repository:
        name: docker
        description: Docker CE Stable - $basearch
        baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
        gpgcheck: yes
        enabled: yes
        gpgkey: https://download.docker.com/linux/centos/gpg
      when:
        - (docker_repo.stat.exists == false)

    - name: Instalando Docker
      yum:
        name:  docker-ce
        state: present
      ignore_errors: yes

    - name: Habilitando o Servico do Docker
      systemd:
        name: docker
        enabled: yes
        state: started
      ignore_errors: yes  
