---
path_docker_repo: "/etc/yum.repos.d/docker.repo"

packages:
  to_install:
    - epel-release
    - yum-utils
    - device-mapper-persistent-data
    - lvm2
    - python3
    - python3-pip

pip:
  to_install:
    - 'docker==5.0.0'
