---
path_docker_repo: "/etc/yum.repos.d/docker.repo"

packages:
  to_install:
    - epel-release
    - yum-utils
    - device-mapper-persistent-data
    - lvm2
    - python2-pip
    - https://cbs.centos.org/kojifiles/packages/python-docker/2.5.1/2.el7/noarch/python2-docker-2.5.1-2.el7.noarch.rpm

pip:
  to_install:
    - 'docker==4.4.4'
